# Generated by Django 4.2.16 on 2024-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='not known', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='comment',
            field=models.TextField(default='no comments', max_length=250),
        ),
    ]
