# Generated by Django 4.2.16 on 2024-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_destination_city_alter_destination_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
