# Generated by Django 4.2.16 on 2024-09-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_destination_comment_alter_destination_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
