# Generated by Django 4.2.16 on 2024-09-23 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_destination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Visit Date'),
        ),
    ]
