# Generated by Django 4.2.16 on 2024-09-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('O', 'Other'), ('C', 'City/Town/Neighborhood/Village'), ('B', 'Beach / Island'), ('W', 'Waterfall'), ('H', 'Hill / Mountain / Cliff'), ('P', 'Park / Forest / Cave'), ('E', 'Entertainment/Amusement Park'), ('Z', 'Zoo / Wildlife Attraction'), ('M', 'Museum / Art Gallery / Market / Festivals & Parades / Exhibition'), ('H', 'Historical/Heritage Attraction'), ('L', 'Landmark / Unique Built Attraction')], default='O', max_length=1),
        ),
    ]
